pickaxeName: ""
pickaxeLore:
  - ""
  - ""

oreRespawn: 10 # Seconds
world: ""

soulBalance: "" # {souls}
oreBreak: "" # {souls}

messages:
  noPickaxeHeld: "<red>You need to hold a pickaxe in order to break ores."

oreChances:
  COAL_ORE: 40.0
  IRON_ORE: 25.0
  COPPER_ORE: 15.0
  GOLD_ORE: 10.0
  DIAMOND_ORE: 5.0
  EMERALD_ORE: 5.0

oreValues:
  COAL_ORE:
    min: 0
    max: 5
  IRON_ORE:
    min: 0
    max: 5
  COPPER_ORE:
    min: 0
    max: 5
  GOLD_ORE:
    min: 0
    max: 5
  DIAMOND_ORE:
    min: 0
    max: 5
  EMERALD_ORE:
    min: 0
    max: 5

enchantIDs: # DO NOT TOUCH
  fortune: "fortune"
  keyFinder: "keyfinder"
  oreRegen: "oreregen"
  excavator: "excavator"
  dupe: "dupe"
  greed: "greed"
  lootFinder: "lootfinder"

lootchances:
  # ADD ITEM CHANCES NEEDED

runeIDs:
  - "test"

EnchantManager: # {fortuneLvl} {kfLvl} {oreRegenLvl} {excavatorLvl} {dupeLvl} {greedLvl} {lfLvl} | {price} | {maxLvl}
  fortune:
    name: ""
    description:
      - ""
    maxLvl: 0
    price: 0
    enchMsg: ""
    chance: 1 # type 1 for 100%

    item: AIR
    slot: 0

  keyfinder:
    name: ""
    description:
      - ""
    maxLvl: 0
    price: 0
    enchMsg: ""
    chance: 1 # type 1 for 100%

    item: AIR
    slot: 0

  excavator:
    name: ""
    description:
      - ""
    maxLvl: 0
    price: 0
    enchMsg: ""
    chance: 1 # type 1 for 100%
    radius: 2 # n^3

    item: AIR
    slot: 0

  duplicator:
    name: ""
    description:
      - ""
    maxLvl: 0
    price: 0
    enchMsg: ""
    chance: 1 # type 1 for 100%

    item: AIR
    slot: 0

  greed:
    name: ""
    description:
      - ""
    maxLvl: 0
    price: 0
    enchMsg: ""
    chance: 1 # type 1 for 100%

    item: AIR
    slot: 0

  lootFinder:
    name: ""
    description:
      - ""
    maxLvl: 0
    price: 0
    enchMsg: ""
    chance: 0

    item: AIR
    slot: 0