pickaxeName: "Pickaxe"
pickaxeLore:
  - ""
  - ""

oreRespawn: 10 # Seconds
world: "world"

soulBalance: "{souls}" # {souls}
oreBreak: "{souls}" # {souls}

messages:
  noPickaxeHeld: "<red>You need to hold a pickaxe in order to break ores."
  baltopPlayer: "<gold>{rank} <white>{player}: <green>{balance}" # {rank}, {player}, {balance}
  maxLevel: "You have already maxed this enchant out."
  insufficientFunds: "You do not have enough souls to pay for this enchant."


oreValues:
  COAL_ORE:
    min: 0
    max: 5
  IRON_ORE:
    min: 0
    max: 5
  COPPER_ORE:
    min: 0
    max: 5
  GOLD_ORE:
    min: 0
    max: 5
  DIAMOND_ORE:
    min: 0
    max: 5
  EMERALD_ORE:
    min: 0
    max: 5

enchantIDs: # DO NOT TOUCH
  fortune: "fortune"
  keyFinder: "keyfinder"
  oreRegen: "oreregen"
  excavator: "excavator"
  dupe: "duplicator"
  greed: "greed"
  lootFinder: "lootfinder"

lootchances:
  # ADD ITEM CHANCES NEEDED

runeIDs: # DO NOT TOUCH
  - "test"

EnchantManager: # {price} | {maxLvl}
  formula: #Px = Px-1 * scale_factor - (Px-1*deduct)
    scale_factor: 1.45
    deduct: 0.10
  fortune:
    name: ""
    description:
      - ""
    maxLvl: 0
    price: 0
    enchMsg: ""
    chance: 1 # type 1 for 100%
    multi: 0

    item: AIR

  keyfinder:
    name: ""
    description:
      - ""
    maxLvl: 0
    price: 0
    enchMsg: ""
    chance: 1 # type 1 for 100%

    item: AIR

  excavator:
    name: ""
    description:
      - ""
    maxLvl: 0
    price: 0
    enchMsg: ""
    chance: 1 # type 1 for 100%
    radius: 2 # n^3

    item: AIR

  duplicator:
    name: ""
    description:
      - ""
    maxLvl: 0
    price: 0
    enchMsg: ""
    chance: 1 # type 1 for 100%

    item: AIR

  greed:
    name: ""
    description:
      - ""
    maxLvl: 0
    price: 0
    enchMsg: ""
    chance: 1 # type 1 for 100%

    item: AIR

  lootFinder:
    name: ""
    description:
      - ""
    maxLvl: 0
    price: 0
    enchMsg: ""
    chance: 0

    item: AIR