name: NoahMiningV2
version: 2.0.8
main: noah.noahMiningV2.NoahMiningV2
api-version: '1.21'
softdepend:
- PlaceholderAPI
- PoaLib
- Vault
commands:
  souladmin:
    permission: op
  souls: null
  pickaxe:
    permission: op
  pdctest:
    permission: op
  animationtest:
    permission: op
  testore:
    permission: op
  itemmanager:
    permission: op
    aliases: im
  soultop: null
  miningreload:
    permission: op
